# version: '3.8'

services:
  backend:
    build:
      context: ./FizzBuzzLightYearAPI
      dockerfile: Dockerfile
    ports:
      - "5012:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./db:/app/db
    networks:
      - app-network
    # Ensure container has permission to write to the volume
    user: "1000:1000" # This matches typical Linux user permissions
    # Add healthcheck to ensure database is accessible
    healthcheck:
      test: ["CMD", "test", "-f", "/app/db/database.db"]
      interval: 10s
      timeout: 3s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:5012/api
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5012/api
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
