version: "3.9"
services:
  backend:
    build:
      context: ./FizzBuzzLightYearAPI
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./db:/app/db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

  # db:
  #   image: nouchka/sqlite3
  #   volumes:
  #     - ./db:/data
